# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/developer/workspace/spiderbite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/developer/workspace/spiderbite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/workspace/spiderbite/CMakeFiles /home/developer/workspace/spiderbite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/developer/workspace/spiderbite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpiderBite

# Build rule for target.
SpiderBite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpiderBite
.PHONY : SpiderBite

# fast build rule for target.
SpiderBite/fast:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/build
.PHONY : SpiderBite/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/main.cpp.s
.PHONY : main.cpp.s

src/BaseResponse.o: src/BaseResponse.cpp.o

.PHONY : src/BaseResponse.o

# target to build an object file
src/BaseResponse.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/BaseResponse.cpp.o
.PHONY : src/BaseResponse.cpp.o

src/BaseResponse.i: src/BaseResponse.cpp.i

.PHONY : src/BaseResponse.i

# target to preprocess a source file
src/BaseResponse.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/BaseResponse.cpp.i
.PHONY : src/BaseResponse.cpp.i

src/BaseResponse.s: src/BaseResponse.cpp.s

.PHONY : src/BaseResponse.s

# target to generate assembly for a file
src/BaseResponse.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/BaseResponse.cpp.s
.PHONY : src/BaseResponse.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/SocketConnection.o: src/SocketConnection.cpp.o

.PHONY : src/SocketConnection.o

# target to build an object file
src/SocketConnection.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/SocketConnection.cpp.o
.PHONY : src/SocketConnection.cpp.o

src/SocketConnection.i: src/SocketConnection.cpp.i

.PHONY : src/SocketConnection.i

# target to preprocess a source file
src/SocketConnection.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/SocketConnection.cpp.i
.PHONY : src/SocketConnection.cpp.i

src/SocketConnection.s: src/SocketConnection.cpp.s

.PHONY : src/SocketConnection.s

# target to generate assembly for a file
src/SocketConnection.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/SocketConnection.cpp.s
.PHONY : src/SocketConnection.cpp.s

src/TextBuffer.o: src/TextBuffer.cpp.o

.PHONY : src/TextBuffer.o

# target to build an object file
src/TextBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextBuffer.cpp.o
.PHONY : src/TextBuffer.cpp.o

src/TextBuffer.i: src/TextBuffer.cpp.i

.PHONY : src/TextBuffer.i

# target to preprocess a source file
src/TextBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextBuffer.cpp.i
.PHONY : src/TextBuffer.cpp.i

src/TextBuffer.s: src/TextBuffer.cpp.s

.PHONY : src/TextBuffer.s

# target to generate assembly for a file
src/TextBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextBuffer.cpp.s
.PHONY : src/TextBuffer.cpp.s

src/TextLexer.o: src/TextLexer.cpp.o

.PHONY : src/TextLexer.o

# target to build an object file
src/TextLexer.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextLexer.cpp.o
.PHONY : src/TextLexer.cpp.o

src/TextLexer.i: src/TextLexer.cpp.i

.PHONY : src/TextLexer.i

# target to preprocess a source file
src/TextLexer.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextLexer.cpp.i
.PHONY : src/TextLexer.cpp.i

src/TextLexer.s: src/TextLexer.cpp.s

.PHONY : src/TextLexer.s

# target to generate assembly for a file
src/TextLexer.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextLexer.cpp.s
.PHONY : src/TextLexer.cpp.s

src/TextReader.o: src/TextReader.cpp.o

.PHONY : src/TextReader.o

# target to build an object file
src/TextReader.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextReader.cpp.o
.PHONY : src/TextReader.cpp.o

src/TextReader.i: src/TextReader.cpp.i

.PHONY : src/TextReader.i

# target to preprocess a source file
src/TextReader.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextReader.cpp.i
.PHONY : src/TextReader.cpp.i

src/TextReader.s: src/TextReader.cpp.s

.PHONY : src/TextReader.s

# target to generate assembly for a file
src/TextReader.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextReader.cpp.s
.PHONY : src/TextReader.cpp.s

src/TextWriter.o: src/TextWriter.cpp.o

.PHONY : src/TextWriter.o

# target to build an object file
src/TextWriter.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextWriter.cpp.o
.PHONY : src/TextWriter.cpp.o

src/TextWriter.i: src/TextWriter.cpp.i

.PHONY : src/TextWriter.i

# target to preprocess a source file
src/TextWriter.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextWriter.cpp.i
.PHONY : src/TextWriter.cpp.i

src/TextWriter.s: src/TextWriter.cpp.s

.PHONY : src/TextWriter.s

# target to generate assembly for a file
src/TextWriter.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/TextWriter.cpp.s
.PHONY : src/TextWriter.cpp.s

src/WebCrawler.o: src/WebCrawler.cpp.o

.PHONY : src/WebCrawler.o

# target to build an object file
src/WebCrawler.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/WebCrawler.cpp.o
.PHONY : src/WebCrawler.cpp.o

src/WebCrawler.i: src/WebCrawler.cpp.i

.PHONY : src/WebCrawler.i

# target to preprocess a source file
src/WebCrawler.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/WebCrawler.cpp.i
.PHONY : src/WebCrawler.cpp.i

src/WebCrawler.s: src/WebCrawler.cpp.s

.PHONY : src/WebCrawler.s

# target to generate assembly for a file
src/WebCrawler.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/WebCrawler.cpp.s
.PHONY : src/WebCrawler.cpp.s

src/ui/MainUI.o: src/ui/MainUI.cpp.o

.PHONY : src/ui/MainUI.o

# target to build an object file
src/ui/MainUI.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/MainUI.cpp.o
.PHONY : src/ui/MainUI.cpp.o

src/ui/MainUI.i: src/ui/MainUI.cpp.i

.PHONY : src/ui/MainUI.i

# target to preprocess a source file
src/ui/MainUI.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/MainUI.cpp.i
.PHONY : src/ui/MainUI.cpp.i

src/ui/MainUI.s: src/ui/MainUI.cpp.s

.PHONY : src/ui/MainUI.s

# target to generate assembly for a file
src/ui/MainUI.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/MainUI.cpp.s
.PHONY : src/ui/MainUI.cpp.s

src/ui/TextBoxUI.o: src/ui/TextBoxUI.cpp.o

.PHONY : src/ui/TextBoxUI.o

# target to build an object file
src/ui/TextBoxUI.cpp.o:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/TextBoxUI.cpp.o
.PHONY : src/ui/TextBoxUI.cpp.o

src/ui/TextBoxUI.i: src/ui/TextBoxUI.cpp.i

.PHONY : src/ui/TextBoxUI.i

# target to preprocess a source file
src/ui/TextBoxUI.cpp.i:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/TextBoxUI.cpp.i
.PHONY : src/ui/TextBoxUI.cpp.i

src/ui/TextBoxUI.s: src/ui/TextBoxUI.cpp.s

.PHONY : src/ui/TextBoxUI.s

# target to generate assembly for a file
src/ui/TextBoxUI.cpp.s:
	$(MAKE) -f CMakeFiles/SpiderBite.dir/build.make CMakeFiles/SpiderBite.dir/src/ui/TextBoxUI.cpp.s
.PHONY : src/ui/TextBoxUI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SpiderBite"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BaseResponse.o"
	@echo "... src/BaseResponse.i"
	@echo "... src/BaseResponse.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/SocketConnection.o"
	@echo "... src/SocketConnection.i"
	@echo "... src/SocketConnection.s"
	@echo "... src/TextBuffer.o"
	@echo "... src/TextBuffer.i"
	@echo "... src/TextBuffer.s"
	@echo "... src/TextLexer.o"
	@echo "... src/TextLexer.i"
	@echo "... src/TextLexer.s"
	@echo "... src/TextReader.o"
	@echo "... src/TextReader.i"
	@echo "... src/TextReader.s"
	@echo "... src/TextWriter.o"
	@echo "... src/TextWriter.i"
	@echo "... src/TextWriter.s"
	@echo "... src/WebCrawler.o"
	@echo "... src/WebCrawler.i"
	@echo "... src/WebCrawler.s"
	@echo "... src/ui/MainUI.o"
	@echo "... src/ui/MainUI.i"
	@echo "... src/ui/MainUI.s"
	@echo "... src/ui/TextBoxUI.o"
	@echo "... src/ui/TextBoxUI.i"
	@echo "... src/ui/TextBoxUI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

